package gui

import (
	_ "embed"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
)

// seedPreferences is the seeded IceWM preferences content (NanoBlue theme,
// the meters/workspaces/LEDs/desktop-button/window-list off, one "run-kit"
// workspace). No menu-curation keys — ShowSettingsMenu/ShowThemesMenu had no
// effect on 2.9.6, and IceWM logs and ignores unknown keys.
//
//go:embed seed/preferences
var seedPreferences []byte

// ProfileDir is the IceWM private config dir rk owns: <StateDir>/icewm —
// the value passed to icewm-session as ICEWM_PRIVCFG. ~/.icewm is never
// touched.
func ProfileDir() (string, error) {
	dir, err := StateDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(dir, "icewm"), nil
}

// SeedProfile seeds the IceWM private config dir: preferences is write-once
// (seeded when absent; user edits persist; deleting the file re-seeds) while
// toolbar and menu are regenerated on every call from the resolved terminal
// and browser (rows only for non-empty names, so a button never names a
// binary that does not exist; the commands are plain binary names, never rk
// paths). Directory 0700, files 0600. seeded reports whether preferences was
// written on this call — the supervisor's log line names the first seed.
func SeedProfile(dir, terminal, browser string) (seeded bool, err error) {
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return false, fmt.Errorf("creating the icewm profile dir: %w", err)
	}
	prefs := filepath.Join(dir, "preferences")
	if _, err := os.Stat(prefs); errors.Is(err, fs.ErrNotExist) {
		if err := os.WriteFile(prefs, seedPreferences, 0o600); err != nil {
			return false, fmt.Errorf("seeding icewm preferences: %w", err)
		}
		seeded = true
	} else if err != nil {
		return false, fmt.Errorf("reading icewm preferences: %w", err)
	}
	if err := writeIcewmApps(filepath.Join(dir, "toolbar"), icewmToolbarContent(terminal, browser)); err != nil {
		return false, err
	}
	if err := writeIcewmApps(filepath.Join(dir, "menu"), icewmMenuContent(terminal, browser)); err != nil {
		return false, err
	}
	return seeded, nil
}

// writeIcewmApps rewrites one generated file (0600); a partial write is
// acceptable on the write path — the file is regenerated on the next start.
func writeIcewmApps(path, content string) error {
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		return fmt.Errorf("writing %s: %w", filepath.Base(path), err)
	}
	return nil
}

// icewmProgRows renders the shared Terminal/Browser rows; the icon names
// ("terminal", "web-browser") are the XDG generic names IceWM looks up in the
// active icon theme.
func icewmProgRows(terminal, browser string) []string {
	rows := []string{}
	if terminal != "" {
		rows = append(rows, "prog Terminal terminal "+terminal)
	}
	if browser != "" {
		rows = append(rows, "prog Browser web-browser "+browser)
	}
	return rows
}

func icewmToolbarContent(terminal, browser string) string {
	lines := append([]string{"# generated by rk gui supervise on every start — edit preferences instead"},
		icewmProgRows(terminal, browser)...)
	return strings.Join(lines, "\n") + "\n"
}

func icewmMenuContent(terminal, browser string) string {
	lines := append([]string{"# generated by rk gui supervise on every start"},
		icewmProgRows(terminal, browser)...)
	lines = append(lines, "separator", "includeprog icewm-menu-fdo --no-sep-others --seps")
	return strings.Join(lines, "\n") + "\n"
}
