package gui

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestSeedProfileFirstSeed(t *testing.T) {
	dir := filepath.Join(t.TempDir(), "icewm")

	seeded, err := SeedProfile(dir, "x-terminal-emulator", "")
	if err != nil {
		t.Fatalf("SeedProfile: %v", err)
	}
	if !seeded {
		t.Error("seeded = false on the first call, want true")
	}

	info, err := os.Stat(dir)
	if err != nil {
		t.Fatalf("Stat dir: %v", err)
	}
	if info.Mode().Perm() != 0o700 {
		t.Errorf("dir mode = %o, want 700", info.Mode().Perm())
	}
	for _, name := range []string{"preferences", "toolbar", "menu"} {
		info, err := os.Stat(filepath.Join(dir, name))
		if err != nil {
			t.Fatalf("Stat %s: %v", name, err)
		}
		if info.Mode().Perm() != 0o600 {
			t.Errorf("%s mode = %o, want 600", name, info.Mode().Perm())
		}
	}

	prefs, err := os.ReadFile(filepath.Join(dir, "preferences"))
	if err != nil {
		t.Fatal(err)
	}
	if string(prefs) != string(seedPreferences) {
		t.Errorf("preferences = %q, want the embedded seed verbatim", prefs)
	}

	toolbar, err := os.ReadFile(filepath.Join(dir, "toolbar"))
	if err != nil {
		t.Fatal(err)
	}
	wantToolbar := "# generated by rk gui supervise on every start — edit preferences instead\nprog Terminal terminal x-terminal-emulator\n"
	if string(toolbar) != wantToolbar {
		t.Errorf("toolbar = %q, want %q (exactly one prog row; no browser resolved)", toolbar, wantToolbar)
	}

	menu, err := os.ReadFile(filepath.Join(dir, "menu"))
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(string(menu), "Browser") {
		t.Errorf("menu = %q, want no Browser row when the browser did not resolve", menu)
	}
	lines := strings.Split(strings.TrimSuffix(string(menu), "\n"), "\n")
	if lines[len(lines)-1] != "includeprog icewm-menu-fdo --no-sep-others --seps" {
		t.Errorf("menu last line = %q, want the includeprog line", lines[len(lines)-1])
	}
}

func TestSeedProfileUserEditSurvives(t *testing.T) {
	dir := filepath.Join(t.TempDir(), "icewm")
	if _, err := SeedProfile(dir, "x-terminal-emulator", ""); err != nil {
		t.Fatalf("first SeedProfile: %v", err)
	}
	edited := []byte("# user's own preferences\nTheme=\"ICE/default.theme\"\n")
	if err := os.WriteFile(filepath.Join(dir, "preferences"), edited, 0o600); err != nil {
		t.Fatal(err)
	}

	seeded, err := SeedProfile(dir, "x-terminal-emulator", "chromium")
	if err != nil {
		t.Fatalf("second SeedProfile: %v", err)
	}
	if seeded {
		t.Error("seeded = true over a user-edited preferences, want false (write-once)")
	}
	prefs, err := os.ReadFile(filepath.Join(dir, "preferences"))
	if err != nil {
		t.Fatal(err)
	}
	if string(prefs) != string(edited) {
		t.Errorf("preferences = %q, want the user edit byte-identical", prefs)
	}

	for _, name := range []string{"toolbar", "menu"} {
		content, err := os.ReadFile(filepath.Join(dir, name))
		if err != nil {
			t.Fatal(err)
		}
		if !strings.Contains(string(content), "prog Browser web-browser chromium") {
			t.Errorf("%s = %q, want the Browser row after the resolution changed", name, content)
		}
	}
}

func TestSeedProfileDeleteReseeds(t *testing.T) {
	dir := filepath.Join(t.TempDir(), "icewm")
	if _, err := SeedProfile(dir, "x-terminal-emulator", ""); err != nil {
		t.Fatalf("first SeedProfile: %v", err)
	}
	if err := os.Remove(filepath.Join(dir, "preferences")); err != nil {
		t.Fatal(err)
	}

	seeded, err := SeedProfile(dir, "x-terminal-emulator", "")
	if err != nil {
		t.Fatalf("re-seed: %v", err)
	}
	if !seeded {
		t.Error("seeded = false after deleting preferences, want true")
	}
	prefs, err := os.ReadFile(filepath.Join(dir, "preferences"))
	if err != nil {
		t.Fatal(err)
	}
	if string(prefs) != string(seedPreferences) {
		t.Errorf("re-seeded preferences = %q, want the embedded seed verbatim", prefs)
	}
}

func TestProfileDirUnderStateDir(t *testing.T) {
	t.Setenv("XDG_STATE_HOME", t.TempDir())
	state, err := StateDir()
	if err != nil {
		t.Fatal(err)
	}
	dir, err := ProfileDir()
	if err != nil {
		t.Fatal(err)
	}
	if want := filepath.Join(state, "icewm"); dir != want {
		t.Errorf("ProfileDir() = %q, want %q", dir, want)
	}
}
