[General]
panels=panel1
[panel1]
plugins=mainmenu,quicklaunch,taskbar,tray,statusnotifier,worldclock
position=Bottom
desktop=0
panelSize=32
iconSize=22
lineCount=1
[mainmenu]
type=mainmenu
[quicklaunch]
type=quicklaunch
alignment=Left
apps\size=0
[taskbar]
type=taskbar
[tray]
type=tray
[statusnotifier]
type=statusnotifier
alignment=Right
[worldclock]
type=worldclock
alignment=Right
formatType=custom
useAdvancedManualFormat=true
customFormat=HH:mm
showTooltip=false
